import sql from "@database/db_engine.ts";

let initialization: Promise<void> | undefined;

async function createSchema(): Promise<void> {
    await sql`
        DO $$
        BEGIN
            IF to_regclass('public."Orthoepy"') IS NOT NULL THEN
                IF to_regclass('public.orthoepy') IS NULL THEN
                    EXECUTE 'ALTER TABLE "Orthoepy" RENAME TO orthoepy';
                ELSE
                    INSERT INTO orthoepy (word)
                    SELECT legacy.word
                    FROM "Orthoepy" AS legacy
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM orthoepy AS current_word
                        WHERE current_word.word = legacy.word
                    );
                END IF;
            END IF;
        END
        $$
    `;

    await sql`
        CREATE TABLE IF NOT EXISTS orthoepy (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            word TEXT NOT NULL
        )
    `;

    await sql`
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT PRIMARY KEY
        )
    `;

    await sql`
        CREATE TABLE IF NOT EXISTS orthoepy_wt (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            word_id BIGINT NOT NULL REFERENCES orthoepy(id) ON DELETE CASCADE,
            weight INTEGER NOT NULL DEFAULT 0,
            CONSTRAINT orthoepy_wt_user_word_unique UNIQUE (user_id, word_id)
        )
    `;

    await sql`
        ALTER TABLE orthoepy_wt
        ALTER COLUMN weight SET DEFAULT 0
    `;

    await sql`
        CREATE INDEX IF NOT EXISTS orthoepy_wt_user_weight_idx
        ON orthoepy_wt (user_id, weight DESC)
    `;
}

export function initializeDatabase(): Promise<void> {
    initialization ??= createSchema();
    return initialization;
}
